version: '2'

services:
  portainer:
    build: .
    container_name: portainer
    hostname: portainer
    ports:
      - 9443:9443
      - 9000:9000
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock